import { StyleSheet } from "react-native";
import type { AppTheme } from "../../../theme";

export function createPlaylistStyles(
  theme: AppTheme,
  resolvedMode: "light" | "dark",
) {
  const isDark = resolvedMode === "dark";
  const cardBackground = isDark ? "#111827" : theme.colors.surface;
  const borderColor = isDark ? "#2D333B" : theme.colors.border;
  const inputBackground = isDark ? "#0B1220" : theme.colors.surfaceMuted;
  const dialogOverlay = isDark
    ? "rgba(2, 6, 23, 0.72)"
    : "rgba(15, 23, 42, 0.48)";

  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: isDark ? "#0D1117" : theme.colors.background,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: isDark ? "#2D333B" : theme.colors.border,
      backgroundColor: isDark ? "#0D1117" : theme.colors.background,
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    backButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    reloadButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      color: isDark ? "#E6EDF3" : theme.colors.text,
      fontSize: 19,
      fontFamily: theme.fonts.semibold,
    },
    content: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 24,
      gap: 12,
    },
    hero: {
      position: "relative",
      borderRadius: 12,
      overflow: "hidden",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      backgroundColor: cardBackground,
    },
    uploadedImage: {
      width: "100%",
      height: 190,
    },
    imagePlaceholder: {
      minHeight: 190,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    uploadImageButton: {
      position: "absolute",
      right: 10,
      bottom: 10,
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "#1F6FEB" : "#2563EB",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "#60A5FA" : "#1D4ED8",
    },
    placeholderIcon: {
      color: isDark ? "#94A3B8" : theme.colors.textMuted,
    },
    placeholderText: {
      color: isDark ? "#C9D1D9" : theme.colors.textMuted,
      fontSize: 15,
      fontFamily: theme.fonts.medium,
    },
    summaryCard: {
      position: "relative",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      borderRadius: 12,
      backgroundColor: cardBackground,
      padding: 14,
      gap: 10,
    },
    summaryCardEditable: {
      paddingBottom: 52,
    },
    editCardButton: {
      position: "absolute",
      right: 12,
      bottom: 12,
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "#60A5FA" : "#1D4ED8",
      backgroundColor: isDark ? "#1F6FEB" : "#2563EB",
      zIndex: 1,
    },
    summaryPlaceholder: {
      minHeight: 130,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    summaryContent: {
      gap: 10,
    },
    summaryTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 40,
    },
    summaryLeftBlock: {
      flex: 1,
      minWidth: 0,
    },
    createdAtBlock: {
      alignItems: "flex-end",
    },
    dmBlock: {
      alignItems: "flex-start",
    },
    playlistTitle: {
      color: isDark ? "#E6EDF3" : theme.colors.text,
      fontSize: 21,
      fontFamily: theme.fonts.semibold,
      textTransform: "lowercase",
    },
    eventSubtitle: {
      color: isDark ? "#B9C5D1" : theme.colors.textMuted,
      fontSize: 15,
      fontFamily: theme.fonts.medium,
      lineHeight: 21,
    },
    metaLabel: {
      color: isDark ? "#8B949E" : theme.colors.textMuted,
      fontSize: 12,
      fontFamily: theme.fonts.regular,
    },
    metaValue: {
      color: isDark ? "#E6EDF3" : theme.colors.text,
      fontSize: 14,
      fontFamily: theme.fonts.medium,
      marginTop: 2,
    },
    songSection: {
      position: "relative",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      borderRadius: 12,
      backgroundColor: cardBackground,
      padding: 12,
      gap: 10,
      paddingBottom: 68,
    },
    songSectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    sectionTitle: {
      color: isDark ? "#E6EDF3" : theme.colors.text,
      fontSize: 16,
      fontFamily: theme.fonts.semibold,
    },
    songListContainer: {
      height: 336,
      borderRadius: 12,
      overflow: "hidden",
    },
    imageLoadingOverlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark
        ? "rgba(13, 17, 23, 0.22)"
        : "rgba(244, 247, 251, 0.28)",
    },
    songListContent: {
      gap: 8,
      paddingBottom: 4,
    },
    songEmptyState: {
      height: 336,
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      paddingHorizontal: 20,
    },
    songEmptyText: {
      color: isDark ? "#94A3B8" : theme.colors.textMuted,
      fontSize: 14,
      fontFamily: theme.fonts.medium,
      textAlign: "center",
    },
    songFooter: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 10,
      gap: 8,
    },
    songFooterText: {
      color: isDark ? "#94A3B8" : theme.colors.textMuted,
      fontSize: 12,
      fontFamily: theme.fonts.regular,
      textAlign: "center",
    },
    songRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 10,
      backgroundColor: isDark ? "#0B1220" : theme.colors.surface,
      gap: 12,
    },
    songLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flex: 1,
    },
    songTextBlock: {
      flex: 1,
      gap: 4,
      minWidth: 0,
    },
    toneBadge: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "#131C2E" : theme.colors.surfaceMuted,
    },
    toneText: {
      color: isDark ? "#E6EDF3" : theme.colors.text,
      fontSize: 14,
      fontFamily: theme.fonts.semibold,
    },
    songName: {
      color: isDark ? "#E6EDF3" : theme.colors.text,
      fontSize: 15,
      fontFamily: theme.fonts.medium,
    },
    songLinkRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    songLinkText: {
      color: isDark ? "#94A3B8" : theme.colors.textMuted,
      fontSize: 12,
      fontFamily: theme.fonts.regular,
      flexShrink: 1,
    },
    songBadgeRight: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: "#CC0000",
      backgroundColor: isDark ? "#2A0F0F" : "#FFF1F2",
    },
    addSongFab: {
      position: "absolute",
      right: 12,
      bottom: 12,
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "#1F6FEB" : theme.colors.primary,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "#60A5FA" : theme.colors.primary,
      shadowColor: "#000",
      shadowOpacity: 0.22,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    addSongFabPressed: {
      opacity: 0.82,
    },
    songToneChipGroup: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      paddingTop: 2,
    },
    songToneChip: {
      minHeight: 34,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      backgroundColor: inputBackground,
      paddingHorizontal: 12,
      paddingVertical: 8,
      gap: 6,
      alignItems: "center",
      justifyContent: "center",
    },
    songToneChipSelected: {
      backgroundColor: isDark ? "#1F6FEB" : theme.colors.primary,
      borderColor: isDark ? "#60A5FA" : theme.colors.primary,
    },
    songToneChipPressed: {
      opacity: 0.82,
    },
    songToneChipText: {
      color: isDark ? "#E6EDF3" : theme.colors.text,
      fontSize: 12,
      fontFamily: theme.fonts.medium,
    },
    songToneChipTextSelected: {
      color: "#FFFFFF",
    },
    dynamicWrap: {
      alignItems: "stretch",
    },
    dynamicButton: {
      width: "100%",
      minHeight: 58,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      borderRadius: 14,
      backgroundColor: isDark ? "#111827" : theme.colors.surface,
      paddingVertical: 14,
      paddingHorizontal: 18,
      gap: 10,
    },
    dynamicButtonText: {
      color: isDark ? "#E6EDF3" : theme.colors.text,
      fontSize: 16,
      fontFamily: theme.fonts.medium,
    },
    dialogOverlay: {
      flex: 1,
      backgroundColor: dialogOverlay,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 18,
    },
    dialogCard: {
      width: "100%",
      maxWidth: 460,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      backgroundColor: cardBackground,
      padding: 14,
      gap: 10,
    },
    dialogTitle: {
      color: isDark ? "#E6EDF3" : theme.colors.text,
      fontSize: 18,
      fontFamily: theme.fonts.semibold,
    },
    dialogField: {
      gap: 6,
    },
    dialogLabel: {
      color: isDark ? "#9AA6B2" : theme.colors.textMuted,
      fontSize: 13,
      fontFamily: theme.fonts.medium,
    },
    dialogInput: {
      minHeight: 42,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      borderRadius: 10,
      backgroundColor: inputBackground,
      color: isDark ? "#E6EDF3" : theme.colors.text,
      fontSize: 14,
      fontFamily: theme.fonts.regular,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    dmChipGroup: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      paddingTop: 2,
    },
    dmChip: {
      minHeight: 34,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      backgroundColor: inputBackground,
      paddingHorizontal: 12,
      paddingVertical: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    dmChipSelected: {
      backgroundColor: isDark ? "#1F6FEB" : theme.colors.primary,
      borderColor: isDark ? "#60A5FA" : theme.colors.primary,
    },
    dmChipPressed: {
      opacity: 0.82,
    },
    dmChipText: {
      color: isDark ? "#E6EDF3" : theme.colors.text,
      fontSize: 14,
      fontFamily: theme.fonts.medium,
    },
    dmChipTextSelected: {
      color: "#FFFFFF",
    },
    dialogPlaceholder: {
      color: isDark ? "#64748B" : "#94A3B8",
    },
    dmEmptyText: {
      color: isDark ? "#8B949E" : theme.colors.textMuted,
      fontSize: 13,
      fontFamily: theme.fonts.regular,
    },
    dialogErrorText: {
      color: "#FB7185",
      fontSize: 12,
      fontFamily: theme.fonts.regular,
    },
    dialogActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 8,
      marginTop: 2,
    },
    dialogCancelButton: {
      minHeight: 38,
      borderRadius: 9,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 12,
      backgroundColor: inputBackground,
    },
    dialogCancelText: {
      color: isDark ? "#CBD5E1" : "#334155",
      fontSize: 13,
      fontFamily: theme.fonts.medium,
    },
    dialogAddButton: {
      minHeight: 38,
      borderRadius: 19,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "#60A5FA" : "#1D4ED8",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 14,
      backgroundColor: isDark ? "#1F6FEB" : "#2563EB",
    },
    dialogAddText: {
      color: "#FFFFFF",
      fontSize: 13,
      fontFamily: theme.fonts.semibold,
    },
    pressed: {
      opacity: 0.8,
    },
  });
}
